<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StateBallot.Core\StateBallot.Core.csproj" />
    <ProjectReference Include="..\StateBallot.States.Ca\StateBallot.States.Ca.csproj" />
    <ProjectReference Include="..\StateBallot.States.Wa\StateBallot.States.Wa.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
